In [2]:
!wget https://github.com/SirYoja/TaskData/raw/refs/heads/main/KaiNet/best_pictures.tar.gz

--2025-04-30 19:05:25--  https://github.com/SirYoja/TaskData/raw/refs/heads/main/KaiNet/best_pictures.tar.gz
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/SirYoja/TaskData/refs/heads/main/KaiNet/best_pictures.tar.gz [following]
--2025-04-30 19:05:25--  https://raw.githubusercontent.com/SirYoja/TaskData/refs/heads/main/KaiNet/best_pictures.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21160383 (20M) [application/octet-stream]
Saving to: ‘best_pictures.tar.gz’

best_pictures.tar.g 100%[===================>]  20.18M  --.-KB/s    in 0.06s   

2025-04-30 19:05:26 (334 MB/s) - ‘best_picture

In [3]:
!tar -xzf best_pictures.tar.gz

tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.lastuseddate#PS'


In [4]:
import torch
from torch import nn
import numpy as np
from matplotlib.image import imread
from torch.utils.data import Dataset, DataLoader, Subset
from tqdm.notebook import tqdm
from sklearn.model_selection import KFold

In [8]:
class DatasetKaiNet(Dataset):
  def __init__(self):
    self.inpictures=[]
    self.outpictures=[]

  def load_pictures(self, number):
    bpath='./'+str(number)+'.png'
    self.inpictures.append(torch.tensor(imread(bpath), dtype=torch.float32).reshape(1,64,64)*255)
    apath='./'+str(number)+'.txt'
    self.outpictures.append(torch.tensor(np.loadtxt(apath), dtype=torch.float32).reshape(1,64,64))

  def __len__(self):
    return len(self.inpictures)

  def __getitem__(self, idx):
    return self.inpictures[idx], self.outpictures[idx]



full_dataset=DatasetKaiNet()
for number in range(1,1001):
  full_dataset.load_pictures(number)



In [9]:
print(imread('1.png')*255)
print(np.loadtxt('1.txt'))

[[174. 160. 172. ... 182. 223. 244.]
 [213. 226. 184. ... 223. 217. 154.]
 [163. 202. 194. ... 165. 127. 135.]
 ...
 [137. 131. 122. ...  99. 100. 114.]
 [136. 129. 118. ...  85.  89. 112.]
 [132. 125. 117. ...  73.  91. 109.]]
[[ 324.81640625  364.234375    353.43359375 ...  326.73828125
   229.59765625   33.4296875 ]
 [ 339.8203125   287.3828125   229.90234375 ...  166.51953125
    54.49609375 -134.234375  ]
 [ 289.40234375  188.03515625  113.96484375 ...   55.84765625
   -46.609375   -207.77734375]
 ...
 [ 227.94921875  131.46875      66.82421875 ...   20.4140625
   -33.46484375 -130.69140625]
 [ 158.03125      54.953125     -8.49609375 ...  -30.85546875
   -69.5234375  -135.56640625]
 [  23.84765625  -83.91796875 -141.98828125 ... -111.99609375
  -124.3828125  -131.65234375]]


In [16]:
train_data_loader=DataLoader(full_dataset, batch_size=1, shuffle=True)

weight1=torch.tensor([[-1.0,-0.5,0.0],[-0.5,0.5,0.5],[0.0,0.5,1.0]])
weight2=torch.tensor([[0.0625,0.0625,0.0625],[0.0625,0.0625,0.0625],[0.0625,0.0625,0.0625]])


weight1=weight1.unsqueeze(0).unsqueeze(0)
weight2=weight2.unsqueeze(0).unsqueeze(0)

In [17]:
class trymodel1(nn.Module):
  def __init__(self):
      super().__init__()
      self.conv1=nn.Conv2d(1,1,3, padding=1, bias=False)
      self.conv2=nn.Conv2d(1,1,3, padding=1, bias=False)
      self.conv3=nn.Conv2d(1,1,3, padding=1, bias=False)

      self.conv3.weight=torch.nn.Parameter(weight1)
      self.conv1.weight=torch.nn.Parameter(weight2)
      self.conv3.weight.requires_grad=False
      self.conv1.weight.requires_grad=False



  def forward(self, x):
      x=self.conv1(x)
      x=self.conv2(x)
      x=self.conv3(x)
      return x

model=trymodel1()
device='cpu'


In [20]:
def train(model, loss_f, opt, train_data_loader, num_epoch):
  for epoch in range(num_epoch):
    train_history=[]
    test_history=[]

    for image, label in tqdm(train_data_loader):
      temp=[]
      temp_test=[]

      opt.zero_grad()
      label_predicted=model(image.to(device))
      loss=loss_f(label_predicted, label.to(device))
      loss.backward()
      opt.step()
      temp.append(loss.item())

    print(np.mean(temp))
    print(epoch+1)
    print('\n')
  return model

loss_f=nn.MSELoss()
opt=torch.optim.Adam(model.parameters(),lr=0.1)
num_epoch=100
model=train(model.to(device), loss_f, opt, train_data_loader,num_epoch)

  0%|          | 0/1000 [00:00<?, ?it/s]

0.0007991400198079646
1




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00021163534256629646
2




  0%|          | 0/1000 [00:00<?, ?it/s]

13.945693969726562
3




  0%|          | 0/1000 [00:00<?, ?it/s]

0.4145103991031647
4




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0006191973225213587
5




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0034627942368388176
6




  0%|          | 0/1000 [00:00<?, ?it/s]

2.6416666969453217e-06
7




  0%|          | 0/1000 [00:00<?, ?it/s]

9.603369107935578e-06
8




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0002958787663374096
9




  0%|          | 0/1000 [00:00<?, ?it/s]

1.8369300960330293e-06
10




  0%|          | 0/1000 [00:00<?, ?it/s]

3.715470711540547e-06
11




  0%|          | 0/1000 [00:00<?, ?it/s]

1.7213700630236417e-05
12




  0%|          | 0/1000 [00:00<?, ?it/s]

4.689462002716027e-06
13




  0%|          | 0/1000 [00:00<?, ?it/s]

2.5595836632419378e-06
14




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00010415147698950022
15




  0%|          | 0/1000 [00:00<?, ?it/s]

3.867455234285444e-05
16




  0%|          | 0/1000 [00:00<?, ?it/s]

2.0459576717257733e-06
17




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00020301991025917232
18




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0421476773917675
19




  0%|          | 0/1000 [00:00<?, ?it/s]

4.076354187532161e-08
20




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0001218700926983729
21




  0%|          | 0/1000 [00:00<?, ?it/s]

1.7320256802122458e-06
22




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0007507156115025282
23




  0%|          | 0/1000 [00:00<?, ?it/s]

2.0167492493783357e-06
24




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00010577525245025754
25




  0%|          | 0/1000 [00:00<?, ?it/s]

2.195793285864056e-06
26




  0%|          | 0/1000 [00:00<?, ?it/s]

2.334423065185547
27




  0%|          | 0/1000 [00:00<?, ?it/s]

5.803439307783265e-06
28




  0%|          | 0/1000 [00:00<?, ?it/s]

3.7860224892938277e-06
29




  0%|          | 0/1000 [00:00<?, ?it/s]

1.7484280760982074e-06
30




  0%|          | 0/1000 [00:00<?, ?it/s]

34.82310485839844
31




  0%|          | 0/1000 [00:00<?, ?it/s]

6.980199032113887e-06
32




  0%|          | 0/1000 [00:00<?, ?it/s]

1.0111492976250247e-08
33




  0%|          | 0/1000 [00:00<?, ?it/s]

4.431055522502447e-09
34




  0%|          | 0/1000 [00:00<?, ?it/s]

9.856815267994534e-06
35




  0%|          | 0/1000 [00:00<?, ?it/s]

1.1544801736818044e-06
36




  0%|          | 0/1000 [00:00<?, ?it/s]

2.683551372228976e-07
37




  0%|          | 0/1000 [00:00<?, ?it/s]

0.001396638574078679
38




  0%|          | 0/1000 [00:00<?, ?it/s]

7.069561888783937e-06
39




  0%|          | 0/1000 [00:00<?, ?it/s]

1.004037585516926e-06
40




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0007254385855048895
41




  0%|          | 0/1000 [00:00<?, ?it/s]

6.040657467565325e-07
42




  0%|          | 0/1000 [00:00<?, ?it/s]

1.63036474987166e-05
43




  0%|          | 0/1000 [00:00<?, ?it/s]

1.324803113937378
44




  0%|          | 0/1000 [00:00<?, ?it/s]

2.8275684599066153e-05
45




  0%|          | 0/1000 [00:00<?, ?it/s]

6.539512469316833e-06
46




  0%|          | 0/1000 [00:00<?, ?it/s]

2.3089771161721728e-07
47




  0%|          | 0/1000 [00:00<?, ?it/s]

117.26326751708984
48




  0%|          | 0/1000 [00:00<?, ?it/s]

9.723967195895966e-07
49




  0%|          | 0/1000 [00:00<?, ?it/s]

5.348725906628715e-08
50




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0721464529633522
51




  0%|          | 0/1000 [00:00<?, ?it/s]

5.367572157410905e-06
52




  0%|          | 0/1000 [00:00<?, ?it/s]

4.457065188034903e-06
53




  0%|          | 0/1000 [00:00<?, ?it/s]

0.037639036774635315
54




  0%|          | 0/1000 [00:00<?, ?it/s]

1.6994717952911742e-05
55




  0%|          | 0/1000 [00:00<?, ?it/s]

9.023843449540436e-05
56




  0%|          | 0/1000 [00:00<?, ?it/s]

1.7593040979591024e-07
57




  0%|          | 0/1000 [00:00<?, ?it/s]

1.3968900702820974e-07
58




  0%|          | 0/1000 [00:00<?, ?it/s]

5.947146892547607
59




  0%|          | 0/1000 [00:00<?, ?it/s]

4.5401225179375615e-06
60




  0%|          | 0/1000 [00:00<?, ?it/s]

8.378845450351946e-06
61




  0%|          | 0/1000 [00:00<?, ?it/s]

0.08384087681770325
62




  0%|          | 0/1000 [00:00<?, ?it/s]

1.3226099326857366e-06
63




  0%|          | 0/1000 [00:00<?, ?it/s]

3.618634139002097e-07
64




  0%|          | 0/1000 [00:00<?, ?it/s]

2.6001195907592773
65




  0%|          | 0/1000 [00:00<?, ?it/s]

2.168898618037929e-06
66




  0%|          | 0/1000 [00:00<?, ?it/s]

3.4029453672701493e-06
67




  0%|          | 0/1000 [00:00<?, ?it/s]

1.5278719729394652e-05
68




  0%|          | 0/1000 [00:00<?, ?it/s]

7.855529702283093e-07
69




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0007184185669757426
70




  0%|          | 0/1000 [00:00<?, ?it/s]

2.190331997553585e-06
71




  0%|          | 0/1000 [00:00<?, ?it/s]

1.1803982488345355e-05
72




  0%|          | 0/1000 [00:00<?, ?it/s]

1.5781050706209498e-06
73




  0%|          | 0/1000 [00:00<?, ?it/s]

2.8356413395158597e-07
74




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00099767348729074
75




  0%|          | 0/1000 [00:00<?, ?it/s]

9.176666537769052e-08
76




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0007299402495846152
77




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0006840363494120538
78




  0%|          | 0/1000 [00:00<?, ?it/s]

9.078474044799805
79




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0002913770149461925
80




  0%|          | 0/1000 [00:00<?, ?it/s]

0.00012914325634483248
81




  0%|          | 0/1000 [00:00<?, ?it/s]

0.26660364866256714
82




  0%|          | 0/1000 [00:00<?, ?it/s]

1.375878582621226e-06
83




  0%|          | 0/1000 [00:00<?, ?it/s]

0.2382890284061432
84




  0%|          | 0/1000 [00:00<?, ?it/s]

8.741669148548681e-07
85




  0%|          | 0/1000 [00:00<?, ?it/s]

4.5235529455567303e-07
86




  0%|          | 0/1000 [00:00<?, ?it/s]

2.8362458692754444e-07
87




  0%|          | 0/1000 [00:00<?, ?it/s]

2.5878416636260226e-06
88




  0%|          | 0/1000 [00:00<?, ?it/s]

1.9853861331939697
89




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0002812599705066532
90




  0%|          | 0/1000 [00:00<?, ?it/s]

2.6450204586581094e-06
91




  0%|          | 0/1000 [00:00<?, ?it/s]

1.6927444903558353e-06
92




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0011099522234871984
93




  0%|          | 0/1000 [00:00<?, ?it/s]

0.0006371147464960814
94




  0%|          | 0/1000 [00:00<?, ?it/s]

1.5045316104078665e-06
95




  0%|          | 0/1000 [00:00<?, ?it/s]

1.23543642871482e-07
96




  0%|          | 0/1000 [00:00<?, ?it/s]

0.2542903423309326
97




  0%|          | 0/1000 [00:00<?, ?it/s]

6.844612130407768e-07
98




  0%|          | 0/1000 [00:00<?, ?it/s]

1.327855443378212e-07
99




  0%|          | 0/1000 [00:00<?, ?it/s]

6.506743431091309
100




In [22]:
model.parameters
model.conv2.weight

Parameter containing:
tensor([[[[0.1245, 0.2516, 0.1236],
          [0.2540, 0.5030, 0.2510],
          [0.1239, 0.2505, 0.1186]]]], requires_grad=True)